---
name: Deploy to Google Cloud Functions
on: push

jobs:
  build-and-push:
    name: Deploy
    environment: google-functions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: nodelist
          runtime: nodejs12
          credentials: ${{ secrets.gcp_credentials }}

      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
